import bcrypt from 'bcryptjs';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import crypto from 'node:crypto';
import express, { type Request, type Response } from 'express';
import rateLimit from 'express-rate-limit';
import fs from 'node:fs';
import { unlink } from 'node:fs/promises';
import path from 'node:path';
import helmet from 'helmet';
import multer from 'multer';
import { z } from 'zod';
import { enquiryStatuses, loginSchema, projectEnquirySchema, talentApplicationSchema, talentStatuses } from '../shared/schemas.ts';
import { issueSession, requireAdmin, requireCsrf } from './middleware/auth.ts';
import { createMailer, sendSubmissionEmails } from './services/email.ts';
import { createSubmission, getRecord, listActivity, listContent, listRecords, logActivity, markDelivery, saveContent, updateContent, updateRecord } from './services/store.ts';

const configSchema=z.object({
  nodeEnv:z.enum(['development','test','production']).default('development'),clientOrigin:z.string().default('http://localhost:5173'),jwtSecret:z.string().min(32).default('development-only-secret-change-before-use'),adminEmail:z.string().email().default('admin@example.com'),adminPasswordHash:z.string().default(''),turnstileSecret:z.string().default(''),uploadDir:z.string().default('./uploads/private'),maxUploadMb:z.coerce.number().positive().max(25).default(8),smtpHost:z.string().optional(),smtpPort:z.coerce.number().default(587),smtpSecure:z.coerce.boolean().default(false),smtpUser:z.string().optional(),smtpPass:z.string().optional(),emailFrom:z.string().default('IT Boutique <hello@example.com>'),notificationEmail:z.string().email().default('hello@example.com'),
}).superRefine((value,ctx)=>{if(value.nodeEnv==='production'){if(value.jwtSecret==='development-only-secret-change-before-use')ctx.addIssue({code:'custom',path:['jwtSecret'],message:'JWT_SECRET must be set in production.'});if(!value.adminPasswordHash)ctx.addIssue({code:'custom',path:['adminPasswordHash'],message:'ADMIN_PASSWORD_HASH must be set in production.'});if(value.adminEmail.endsWith('@example.com'))ctx.addIssue({code:'custom',path:['adminEmail'],message:'ADMIN_EMAIL must be configured in production.'})}});
export type AppConfig=z.infer<typeof configSchema>;
export function getConfig(overrides:Partial<AppConfig>={}):AppConfig{return configSchema.parse({nodeEnv:process.env.NODE_ENV,clientOrigin:process.env.CLIENT_ORIGIN,jwtSecret:process.env.JWT_SECRET,adminEmail:process.env.ADMIN_EMAIL,adminPasswordHash:process.env.ADMIN_PASSWORD_HASH,turnstileSecret:process.env.TURNSTILE_SECRET_KEY,uploadDir:process.env.UPLOAD_DIR,maxUploadMb:process.env.MAX_UPLOAD_MB,smtpHost:process.env.SMTP_HOST,smtpPort:process.env.SMTP_PORT,smtpSecure:process.env.SMTP_SECURE,smtpUser:process.env.SMTP_USER,smtpPass:process.env.SMTP_PASS,emailFrom:process.env.EMAIL_FROM,notificationEmail:process.env.ADMIN_NOTIFICATION_EMAIL,...overrides})}

// eslint-disable-next-line no-control-regex
function clean(value:unknown):unknown{if(typeof value==='string')return value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').trim();if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,clean(v)]));return value}
function reference(prefix:'ENQ'|'TAL'){const date=new Date().toISOString().slice(0,10).replaceAll('-','');return`${prefix}-${date}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`}
function idempotency(req:Request){const value=req.get('Idempotency-Key');if(!value||value.length<12||value.length>120||!/^[a-zA-Z0-9-]+$/.test(value))throw new Error('A valid idempotency key is required.');return value}
async function verifyTurnstile(token:string|undefined,secret:string,ip:string|undefined){if(!secret)return true;if(!token)return false;try{const body=new URLSearchParams({secret,response:token,...(ip?{remoteip:ip}:{})});const response=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body});const result=await response.json() as {success:boolean};return result.success}catch{return false}}
function csv(items:Record<string,unknown>[]){if(!items.length)return'reference,name,email,status,createdAt\n';const keys=['reference','name','email','organization','role','service','status','createdAt'];const escape=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;return`${keys.join(',')}\n${items.map(row=>keys.map(key=>escape(row[key])).join(',')).join('\n')}\n`}

export function createApp(input:Partial<AppConfig>={}){
  const config=getConfig(input);fs.mkdirSync(path.resolve(config.uploadDir),{recursive:true});
  const storage=multer.diskStorage({destination:config.uploadDir,filename:(_req,file,cb)=>cb(null,`${Date.now()}-${crypto.randomBytes(12).toString('hex')}${path.extname(file.originalname).toLowerCase()}`)});
  const allowed=new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','image/png','image/jpeg']);
  const upload=multer({storage,limits:{fileSize:config.maxUploadMb*1024*1024,files:1},fileFilter:(_req,file,cb)=>allowed.has(file.mimetype)?cb(null,true):cb(new Error('Unsupported file type.'))});
  const app=express();app.set('trust proxy',1);app.disable('x-powered-by');
  app.use(helmet({contentSecurityPolicy:config.nodeEnv==='production'?undefined:false,crossOriginResourcePolicy:{policy:'same-site'}}));
  app.use(cors({origin:config.clientOrigin,credentials:true,methods:['GET','POST','PATCH','OPTIONS'],allowedHeaders:['Content-Type','Idempotency-Key','X-CSRF-Token']}));app.use(cookieParser());
  const publicLimiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:'draft-7',legacyHeaders:false,message:{message:'Too many submissions. Please wait and try again.'}});
  const loginLimiter=rateLimit({windowMs:15*60*1000,limit:8,standardHeaders:'draft-7',legacyHeaders:false,message:{message:'Too many login attempts. Please wait and try again.'}});
  const mailConfig={host:config.smtpHost,port:config.smtpPort,secure:config.smtpSecure,user:config.smtpUser,pass:config.smtpPass,from:config.emailFrom,adminEmail:config.notificationEmail};const mailer=createMailer(mailConfig);

  app.get('/api/health',(_req,res)=>res.json({ok:true,service:'it-boutique-api'}));
  const accept=(kind:'enquiries'|'talent')=>(req:Request,res:Response)=>upload.single('attachment')(req,res,async error=>{if(error)return res.status(400).json({message:error instanceof multer.MulterError&&error.code==='LIMIT_FILE_SIZE'?`File must be ${config.maxUploadMb} MB or smaller.`:'File type or upload is not allowed.'});try{const raw=typeof req.body.payload==='string'?JSON.parse(req.body.payload):{};const safe=clean(raw);const schema=kind==='enquiries'?projectEnquirySchema:talentApplicationSchema;const parsed=schema.parse(safe);if(kind==='talent'&&!req.file)return res.status(400).json({message:'A CV file is required.'});const turnstile=await verifyTurnstile(parsed.turnstileToken,config.turnstileSecret,req.ip);if(!turnstile){if(req.file)await unlink(req.file.path).catch(()=>undefined);return res.status(400).json({message:'Anti-spam verification failed. Please retry.'})}const key=idempotency(req);const prefix=kind==='enquiries'?'ENQ':'TAL';const attachment=req.file?{originalName:req.file.originalname,storedName:req.file.filename,mimeType:req.file.mimetype,size:req.file.size}:undefined;const created=await createSubmission(kind,{...parsed,turnstileToken:undefined,reference:reference(prefix),idempotencyKey:key,consentAt:new Date(),attachment,status:'New',archived:false});const record=created.record as Record<string,unknown>;if(created.duplicate&&req.file)await unlink(req.file.path).catch(()=>undefined);if(!created.duplicate){await logActivity('public','created',kind,String(record._id),{reference:record.reference});const delivery=await sendSubmissionEmails(mailer,mailConfig,{email:String(record.email),name:String(record.name),reference:String(record.reference),kind:kind==='enquiries'?'project enquiry':'talent profile'});await markDelivery(kind,String(record._id),delivery.status);if(delivery.status==='partial-failure')await logActivity('system','email-delivery-failure',kind,String(record._id),{reference:record.reference})}return res.status(created.duplicate?200:201).json({reference:record.reference,message:'Your submission has been securely received.'})}catch(error){if(req.file)await unlink(req.file.path).catch(()=>undefined);if(error instanceof z.ZodError)return res.status(400).json({message:'Please review the form fields.',issues:error.issues.map(issue=>({path:issue.path.join('.'),message:issue.message}))});const message=error instanceof Error&&error.message.includes('idempotency')?error.message:'We could not preserve this submission. Please retry.';console.error('Submission error',error);return res.status(500).json({message})}});
  app.post('/api/enquiries',publicLimiter,accept('enquiries'));app.post('/api/talent',publicLimiter,accept('talent'));

  app.use('/api/admin',express.json({limit:'250kb'}));
  app.post('/api/admin/login',loginLimiter,async(req,res)=>{const parsed=loginSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({message:'Enter a valid email and password.'});if(!config.adminPasswordHash)return res.status(503).json({message:'Admin access is not configured.'});const suppliedEmail=crypto.createHash('sha256').update(parsed.data.email.toLowerCase()).digest();const configuredEmail=crypto.createHash('sha256').update(config.adminEmail.toLowerCase()).digest();const emailMatch=crypto.timingSafeEqual(suppliedEmail,configuredEmail);const passwordMatch=await bcrypt.compare(parsed.data.password,config.adminPasswordHash);if(!emailMatch||!passwordMatch){await logActivity(parsed.data.email,'login-failed','session');return res.status(401).json({message:'Email or password is incorrect.'})}const session=issueSession(parsed.data.email,config.jwtSecret);res.cookie('admin_session',session.token,{httpOnly:true,secure:config.nodeEnv==='production',sameSite:'strict',maxAge:8*60*60*1000,path:'/'});await logActivity(parsed.data.email,'login-success','session');return res.json({csrfToken:session.csrf})});
  const auth=requireAdmin(config.jwtSecret);app.use('/api/admin',auth);app.use('/api/admin',requireCsrf);
  app.get('/api/admin/session',(req,res)=>res.json({authenticated:true,csrfToken:res.locals.admin.csrf}));app.post('/api/admin/logout',async(_req,res)=>{await logActivity(res.locals.admin.sub,'logout','session');res.clearCookie('admin_session',{path:'/'});res.json({ok:true})});
  for(const kind of ['enquiries','talent'] as const){app.get(`/api/admin/${kind}`,async(req,res)=>res.json({items:await listRecords(kind,String(req.query.q||''))}));app.get(`/api/admin/${kind}/export`,async(_req,res)=>{const items=await listRecords(kind);res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename="${kind}-${new Date().toISOString().slice(0,10)}.csv"`);res.send(csv(items as Record<string,unknown>[]))});app.patch(`/api/admin/${kind}/:id`,async(req,res)=>{const allowedStatus=kind==='enquiries'?enquiryStatuses:talentStatuses;const patchSchema=z.object({status:z.enum(allowedStatus).optional(),internalNotes:z.string().max(5000).optional(),archived:z.boolean().optional()}).strict();const parsed=patchSchema.safeParse(clean(req.body));if(!parsed.success)return res.status(400).json({message:'Invalid update.'});const updated=await updateRecord(kind,req.params.id,parsed.data);if(!updated)return res.status(404).json({message:'Record not found.'});await logActivity(res.locals.admin.sub,'updated',kind,req.params.id,parsed.data);res.json({item:updated})});}
  app.get('/api/admin/files/:kind/:id',async(req,res)=>{if(!['enquiries','talent'].includes(req.params.kind))return res.status(404).end();const record=await getRecord(req.params.kind as 'enquiries'|'talent',req.params.id) as Record<string,unknown>|null;const attachment=record?.attachment as {storedName?:unknown;mimeType?:unknown;originalName?:unknown}|undefined;if(!attachment?.storedName)return res.status(404).json({message:'File not found.'});const filePath=path.resolve(config.uploadDir,String(attachment.storedName));const base=path.resolve(config.uploadDir)+path.sep;if(!filePath.startsWith(base))return res.status(400).json({message:'Invalid file path.'});res.setHeader('Content-Type',String(attachment.mimeType));res.setHeader('Content-Disposition',`attachment; filename="${String(attachment.originalName).replaceAll('"','')}"`);res.sendFile(filePath)});
  app.get('/api/admin/content',async(req,res)=>res.json({items:await listContent(String(req.query.type||''))}));app.post('/api/admin/content',async(req,res)=>{const schema=z.object({type:z.enum(contentTypes),title:z.string().min(2).max(160),slug:z.string().regex(/^[a-z0-9-]+$/).max(160),data:z.record(z.string(),z.unknown())});const parsed=schema.safeParse(clean(req.body));if(!parsed.success)return res.status(400).json({message:'Invalid content record.'});const item=await saveContent(parsed.data);await logActivity(res.locals.admin.sub,'saved','content',String((item as Record<string,unknown>)._id),{type:parsed.data.type,slug:parsed.data.slug});res.status(201).json({item})});app.patch('/api/admin/content/:id',async(req,res)=>{const parsed=z.object({archived:z.boolean().optional(),title:z.string().min(2).max(160).optional(),data:z.record(z.string(),z.unknown()).optional()}).strict().safeParse(clean(req.body));if(!parsed.success)return res.status(400).json({message:'Invalid content update.'});const item=await updateContent(req.params.id,parsed.data);if(!item)return res.status(404).json({message:'Content record not found.'});await logActivity(res.locals.admin.sub,'updated','content',req.params.id,parsed.data);res.json({item})});app.get('/api/admin/activity',async(_req,res)=>res.json({items:await listActivity()}));
  app.use('/api',(req,res)=>res.status(404).json({message:'API route not found.'}));
  if(config.nodeEnv==='production'){const dist=path.resolve('dist');app.use(express.static(dist,{maxAge:'1y',immutable:true,index:false}));app.use((req,res,next)=>{if(req.method!=='GET')return next();res.sendFile(path.join(dist,'index.html'))})}
  app.use((error:unknown,_req:Request,res:Response,next:unknown)=>{void next;console.error('Unhandled request error',error);res.status(500).json({message:'An unexpected server error occurred.'})});return app;
}

const contentTypes=['projects','case-studies','services','industries','insights','testimonials','contact'] as const;
