import { ArrowDownRight, Globe2, ShieldCheck } from 'lucide-react';
import { FinalCTA } from '../components/Layout';
import { EditorialPageHero } from '../components/EditorialPageHero';
import { SEO } from '../components/SEO';
import { ButtonLink, SectionIntro } from '../components/ui';
import { principles } from '../content/site';

export default function AboutPage() {
  return <>
    <SEO title="About" description="An international, founder-led technology consultancy launching from the Netherlands and helping organizations build reliable digital systems." path="/about"/>
    <EditorialPageHero variant="editorial" eyebrow="About the consultancy" title="Technical depth, direct collaboration and a commitment to useful outcomes." description="We are a founder-led technology consultancy building reliable systems for organizations doing meaningful work." breadcrumbs={[{label:'Home',to:'/'},{label:'About'}]}/>
    <section className="section"><div className="container-shell grid lg:grid-cols-[.7fr_1.3fr] gap-12 lg:gap-28"><div><p className="eyebrow text-[#167d63]">Our story</p></div><div><h2 className="heading-xl">Built from hands-on delivery—not agency theatre.</h2><div className="body-lg mt-7 grid gap-5"><p>The consultancy has delivered seven-plus systems now used in production. Its next chapter is to bring that practical experience to schools, businesses, nonprofits, ministries and international partners that value close technical collaboration.</p><p>We stay intentionally focused. Clients work directly with the technical lead, while trusted specialists join when a project calls for additional product, design, data, cloud or delivery expertise.</p><p className="text-sm !text-[#8a5a1f] bg-[#f4e6cf] border border-[#e5c99f] rounded-lg p-4">Founder biography, company origin details and approved portrait are still required before launch.</p></div></div></div></section>
    <section className="section bg-[#8ef0c7]"><div className="container-shell grid lg:grid-cols-2 gap-16"><div><p className="eyebrow">Mission</p><h2 className="heading-xl mt-6">To make reliable digital systems accessible to organizations doing meaningful work.</h2></div><div><p className="eyebrow">Vision</p><h2 className="heading-xl mt-6">A future where growing organizations can use technology with clarity, confidence and control.</h2></div></div></section>
    <section className="section"><div className="container-shell"><SectionIntro eyebrow="Operating principles" title="The standards behind the work."/><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{principles.map(item=>{const Icon=item.icon;return <div className="flow-cell card p-6 min-h-52 flex flex-col" key={item.name}><Icon className="text-[#167d63]"/><h3 className="heading-md mt-auto">{item.name}</h3></div>})}</div></div></section>
    <section className="section bg-ink text-white"><div className="container-shell grid lg:grid-cols-2 gap-16 items-start"><div><Globe2 size={38} className="text-mint"/><h2 className="heading-xl mt-8">Based in the Netherlands.<br/>Built for international delivery.</h2></div><div><p className="body-lg !text-[#b6c1c5]">From our European base, projects are structured for organizations across borders through clear decision points, accessible documentation, time-zone-aware communication and visible progress.</p><div className="mt-10"><ButtonLink to="/start-a-project">Work with us</ButtonLink></div></div></div></section>
    <section className="section"><div className="container-shell detail-layout"><div><ShieldCheck size={34} className="text-[#167d63]"/><h2 className="heading-xl mt-7 liquid-heading">Responsible by default.</h2></div><div className="grid gap-6">{['Security is considered from discovery through support.','Client data and confidential context are handled with care.','AI is used where it is valuable, evaluated and appropriately supervised.','Maintainability and knowledge transfer matter after launch.'].map(item=><div className="liquid-line flex justify-between gap-6 border-b border-black/15 pb-6" key={item}><p className="heading-md">{item}</p><ArrowDownRight className="flow-arrow shrink-0 text-[#167d63]"/></div>)}</div></div></section>
    <section className="section-sm bg-white"><div className="container-shell flex flex-col md:flex-row justify-between gap-8 items-start md:items-center"><div><p className="eyebrow text-[#167d63]">Flexible specialist network</p><h2 className="heading-lg mt-5">Bring your expertise to future project teams.</h2></div><ButtonLink to="/join" variant="outline">Join the network</ButtonLink></div></section><FinalCTA/>
  </>;
}
