import { Archive, Download, LogOut, RefreshCw, Save, Search, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { company, projects, services } from '../content/site';

type RecordItem={_id:string;reference:string;name:string;email:string;organization?:string;role?:string;status:string;createdAt:string;internalNotes?:string;attachment?:{originalName:string}};
type ContentItem={_id:string;type:string;title:string;slug:string;data:Record<string,unknown>;archived:boolean;updatedAt:string};
const enquiryStatuses=['New','Reviewing','Discovery scheduled','Proposal sent','Won','On hold','Closed'];
const talentStatuses=['New','Reviewing','Shortlisted','Talent pool','Contacted','Not currently suitable','Archived'];
const contentTypes=['projects','case-studies','services','industries','insights','testimonials','contact'];

async function api(path:string,options:RequestInit={}){const csrf=sessionStorage.getItem('admin-csrf');const headers=new Headers(options.headers);if(csrf)headers.set('X-CSRF-Token',csrf);if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const response=await fetch(path,{...options,credentials:'include',headers});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Request failed');return data;}

function Login({onSuccess}:{onSuccess:()=>void}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const result=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email,password})});sessionStorage.setItem('admin-csrf',result.csrfToken);onSuccess();}catch(err){setError(err instanceof Error?err.message:'Login failed')}};return <main className="min-h-screen bg-ink grid place-items-center p-4"><form onSubmit={submit} className="form-card w-full max-w-md"><div className="brand !text-ink"><span className="brand-mark !border-ink/30 !text-[#167d63]">IT</span><span>{company.name}</span></div><ShieldCheck size={34} className="text-[#167d63] mt-10"/><h1 className="heading-lg mt-5">Secure administration</h1><p className="text-sm text-subtle mt-3 mb-8">Access is restricted, logged and protected with an HTTP-only session cookie.</p><div className="field"><label htmlFor="admin-email">Email</label><input id="admin-email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field mt-4"><label htmlFor="admin-password">Password</label><input id="admin-password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<div className="form-status error" role="alert">{error}</div>}<button className="btn btn-dark mt-6 w-full">Sign in</button></form></main>}

export default function AdminPage(){const [authenticated,setAuthenticated]=useState<boolean|null>(null);const check=useCallback(()=>api('/api/admin/session').then((r)=>{sessionStorage.setItem('admin-csrf',r.csrfToken);setAuthenticated(true)}).catch(()=>setAuthenticated(false)),[]);useEffect(()=>{void check()},[check]);if(authenticated===null)return <main className="min-h-screen grid place-items-center">Checking secure session…</main>;if(!authenticated)return <Login onSuccess={()=>setAuthenticated(true)}/>;return <Dashboard onLogout={()=>{setAuthenticated(false);sessionStorage.removeItem('admin-csrf')}}/>}

function Dashboard({onLogout}:{onLogout:()=>void}){const [tab,setTab]=useState<'enquiries'|'talent'|'content'|'activity'>('enquiries');const logout=async()=>{await api('/api/admin/logout',{method:'POST'}).catch(()=>undefined);onLogout()};return <div className="admin-shell"><header className="admin-header"><div className="container-shell flex items-center justify-between"><div className="brand"><span className="brand-mark">IT</span><span>{company.name} Admin</span></div><button onClick={logout} className="flex items-center gap-2 text-sm"><LogOut size={16}/> Sign out</button></div></header><div className="admin-grid"><aside className="admin-sidebar"><nav className="grid gap-2">{(['enquiries','talent','content','activity'] as const).map(item=><button key={item} onClick={()=>setTab(item)} className={`text-left capitalize rounded-lg p-3 text-sm font-bold ${tab===item?'bg-ink text-white':'hover:bg-[#edf0ee]'}`}>{item}</button>)}</nav><div className="mt-10 border-t pt-5 text-xs text-subtle"><p>{projects.length} project placeholders</p><p className="mt-2">{services.length} configured services</p></div></aside><main className="admin-main">{tab==='enquiries'&&<RecordTable type="enquiries" statuses={enquiryStatuses}/>} {tab==='talent'&&<RecordTable type="talent" statuses={talentStatuses}/>} {tab==='content'&&<ContentManager/>}{tab==='activity'&&<ActivityLog/>}</main></div></div>}

function RecordTable({type,statuses}:{type:'enquiries'|'talent';statuses:string[]}){const [items,setItems]=useState<RecordItem[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);api(`/api/admin/${type}?q=${encodeURIComponent(query)}`).then(r=>setItems(r.items||[])).finally(()=>setLoading(false))},[query,type]);useEffect(()=>{const timer=setTimeout(load,200);return()=>clearTimeout(timer)},[load]);const update=async(item:RecordItem,patch:Record<string,unknown>)=>{await api(`/api/admin/${type}/${item._id}`,{method:'PATCH',body:JSON.stringify(patch)});load()};return <><div className="flex flex-wrap justify-between gap-4 items-center mb-7"><div><p className="eyebrow text-[#167d63]">Operations</p><h1 className="heading-lg mt-3 capitalize">{type}</h1></div><a className="btn btn-outline" href={`/api/admin/${type}/export`}><Download size={16}/> Export CSV</a></div><div className="search-wrap max-w-md mb-5"><Search size={16}/><input className="search-input" placeholder="Search name, email or reference" value={query} onChange={e=>setQuery(e.target.value)}/></div>{loading?<p>Loading records…</p>:items.length===0?<div className="card bg-white p-10"><h2 className="heading-md">No records yet.</h2><p className="text-subtle mt-3">New submissions will appear here after database storage succeeds.</p></div>:<table className="data-table"><thead><tr><th>Reference</th><th>Contact</th><th>Context</th><th>Status</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item._id}><td><b>{item.reference}</b><br/><span className="text-subtle">{new Date(item.createdAt).toLocaleDateString()}</span>{item.attachment&&<><br/><a className="underline" href={`/api/admin/files/${type}/${item._id}`}>Download {item.attachment.originalName}</a></>}</td><td>{item.name}<br/><a href={`mailto:${item.email}`}>{item.email}</a></td><td>{item.organization||item.role}</td><td><select value={item.status} onChange={e=>void update(item,{status:e.target.value})} className="filter-select !rounded-md !min-h-9">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><textarea className="border rounded p-2 min-w-48" defaultValue={item.internalNotes||''} id={`notes-${item._id}`} aria-label={`Internal notes for ${item.reference}`}/></td><td><div className="flex gap-2"><button title="Save notes" onClick={()=>{const el=document.getElementById(`notes-${item._id}`) as HTMLTextAreaElement;void update(item,{internalNotes:el.value})}}><Save size={17}/></button><button title="Archive record" onClick={()=>void update(item,{archived:true})}><Archive size={17}/></button></div></td></tr>)}</tbody></table>}</>}

function ContentManager(){const [type,setType]=useState('projects');const [items,setItems]=useState<ContentItem[]>([]);const [title,setTitle]=useState('');const [slug,setSlug]=useState('');const [data,setData]=useState('{}');const [message,setMessage]=useState('');const load=useCallback(()=>api(`/api/admin/content?type=${type}`).then(r=>setItems(r.items||[])),[type]);useEffect(()=>{void load()},[load]);const save=async()=>{try{await api('/api/admin/content',{method:'POST',body:JSON.stringify({type,title,slug,data:JSON.parse(data)})});setTitle('');setSlug('');setData('{}');setMessage('Content record saved.');load()}catch(err){setMessage(err instanceof Error?err.message:'Could not save')}};return <><p className="eyebrow text-[#167d63]">Structured content</p><h1 className="heading-lg mt-3">Content manager</h1><p className="text-sm text-subtle mt-3 max-w-2xl">Manage CMS-ready records. Public content remains intentionally config-first until approved data is imported.</p><div className="filter-bar mt-6">{contentTypes.map(x=><button className={`btn ${type===x?'btn-dark':'btn-outline'} !min-h-10 !py-1`} onClick={()=>setType(x)} key={x}>{x}</button>)}</div><div className="grid lg:grid-cols-2 gap-5"><div className="form-card"><h2 className="heading-md">New {type} record</h2><div className="field mt-5"><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field mt-4"><label>Slug</label><input value={slug} onChange={e=>setSlug(e.target.value)}/></div><div className="field mt-4"><label>Structured JSON</label><textarea className="font-mono text-xs !min-h-60" value={data} onChange={e=>setData(e.target.value)}/></div><button className="btn btn-dark mt-5" onClick={()=>void save()} disabled={!title||!slug}><Save size={16}/> Save record</button>{message&&<p className="form-status success">{message}</p>}</div><div className="grid gap-3 content-start">{items.map(item=><div className="card bg-white p-5" key={item._id}><div className="flex justify-between gap-4"><div><span className="tag">{item.type}</span><h3 className="font-bold mt-3">{item.title}</h3><p className="text-xs text-subtle mt-1">/{item.slug}</p></div><button title="Archive" onClick={()=>api(`/api/admin/content/${item._id}`,{method:'PATCH',body:JSON.stringify({archived:true})}).then(load)}><Archive size={17}/></button></div></div>)}</div></div></>}

function ActivityLog(){const [items,setItems]=useState<Array<{_id:string;action:string;entityType:string;entityId?:string;createdAt:string}>>([]);const load=useCallback(()=>api('/api/admin/activity').then(r=>setItems(r.items||[])),[]);useEffect(()=>{void load()},[load]);return <><div className="flex items-center justify-between"><div><p className="eyebrow text-[#167d63]">Audit trail</p><h1 className="heading-lg mt-3">Activity log</h1></div><button onClick={()=>void load()} className="btn btn-outline"><RefreshCw size={16}/> Refresh</button></div><div className="mt-7 grid gap-2">{items.map(item=><div className="card bg-white p-4 grid grid-cols-[1fr_auto] gap-4" key={item._id}><p><b>{item.action}</b> <span className="text-subtle">{item.entityType} {item.entityId||''}</span></p><time className="text-xs text-subtle">{new Date(item.createdAt).toLocaleString()}</time></div>)}</div></>}
