import { zodResolver } from '@hookform/resolvers/zod';
import { CircleCheckBig, Globe2, Puzzle, Waypoints } from 'lucide-react';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';
import type { z } from 'zod';
import { talentApplicationSchema } from '../../shared/schemas';
import { SEO } from '../components/SEO';
import { EditorialPageHero } from '../components/EditorialPageHero';
import { TurnstileField } from '../components/TurnstileField';
import { Accordion, ButtonLink, Field, Input, Select, SubmitButton, Textarea } from '../components/ui';
import { company, specialistRoles } from '../content/site';
import { submitWithRecovery } from '../lib/api';

type FormValues=z.input<typeof talentApplicationSchema>;
const engagement=['Freelance','Contract','Part-time collaboration','Internship or mentorship interest','Future full-time opportunity'];

export default function JoinPage(){
  const navigate=useNavigate(); const [file,setFile]=useState<File>(); const [status,setStatus]=useState<{kind:'idle'|'sending'|'error';message?:string}>({kind:'idle'});
  const {register,handleSubmit,setValue,formState:{errors}}=useForm<FormValues>({resolver:zodResolver(talentApplicationSchema),defaultValues:{consent:false,turnstileToken:''}});
  const submit=handleSubmit(async data=>{if(!file){setStatus({kind:'error',message:'Please attach your CV.'});return;}if(file.size>8*1024*1024){setStatus({kind:'error',message:'Your CV must be 8 MB or smaller.'});return;}setStatus({kind:'sending',message:'Securing your profile…'});const result=await submitWithRecovery('/api/talent',data as Record<string,unknown>,file);if(result.ok)navigate(`/submission-success?type=talent&reference=${encodeURIComponent(result.reference)}`);else setStatus({kind:'error',message:`Delivery is not yet confirmed. A recoverable copy remains in this browser. Please retry. ${result.message}`});});
  const networkFaq=[{q:'Does joining guarantee work?',a:'No. The network supports future collaboration. Suitable applicants may be contacted when a relevant opportunity becomes available.'},{q:'Where can applicants be based?',a:'Profiles are welcome from specialists across Europe and worldwide. Availability and timezone help with project matching.'},{q:'How is my CV handled?',a:'It is stored as a private file and only accessible to authorized administrators through a protected endpoint.'},{q:'Can I update my profile later?',a:'Yes. Contact the consultancy with your reference number to request an update or deletion.'}];
  return <><SEO title="Join our talent network" description="Developers, designers, data specialists and technology professionals can register interest in future project collaboration." path="/join"/>
    <EditorialPageHero variant="editorial" eyebrow="Join our talent network" title="Bring your skills to work that creates practical impact." description="We connect trusted developers, designers and technology specialists with suitable project opportunities as the consultancy grows. Joining does not guarantee immediate work or employment." breadcrumbs={[{label:'Home',to:'/'},{label:'Join our talent network'}]} actions={<ButtonLink to="#talent-application">Join the network</ButtonLink>}/><span id="talent-application" className="block scroll-mt-24"/>
    <section className="section-sm bg-[#8ef0c7]"><div className="container-shell grid md:grid-cols-3 gap-8">{[[Puzzle,'Relevant matching','Profiles are considered when a project needs your specific strengths.'],[Waypoints,'Clear engagement','Scope, availability, rates and responsibilities are agreed before work begins.'],[Globe2,'Distributed collaboration','Professionals across Europe and worldwide are welcome.']].map(([Icon,title,text])=><div key={title as string}><Icon/><h2 className="heading-md mt-8">{title as string}</h2><p className="mt-3 text-sm leading-relaxed text-[#40545c]">{text as string}</p></div>)}</div></section>
    <section className="section"><div className="container-shell form-shell"><aside><p className="eyebrow text-[#167d63]">What we value</p><h2 className="heading-lg mt-6">Strong craft, honest communication and respect for the people using what we build.</h2><ul className="bullet-list mt-9">{['Dependable delivery','Thoughtful problem-solving','Security and confidentiality','Constructive collaboration','Documentation and maintainability','Willingness to learn'].map(x=><li key={x}>{x}</li>)}</ul><p className="mt-9 p-4 rounded-lg bg-[#f4e6cf] text-sm text-[#704617]">Joining the network does not guarantee immediate work or employment. Suitable applicants may be contacted when relevant opportunities become available.</p></aside>
      <form className="form-card" onSubmit={submit} noValidate><h2 className="heading-md">Talent profile</h2><p className="mt-2 mb-8 text-sm text-subtle">Fields marked with * are required.</p><div className="form-grid">
        <Field label="Full name *" error={errors.name?.message}><Input autoComplete="name" {...register('name')}/></Field><Field label="Email address *" error={errors.email?.message}><Input type="email" autoComplete="email" {...register('email')}/></Field>
        <Field label="Phone or WhatsApp *" error={errors.phone?.message}><Input type="tel" {...register('phone')}/></Field><Field label="Country and timezone *" error={errors.countryTimezone?.message}><Input placeholder="Netherlands · CET/CEST" {...register('countryTimezone')}/></Field>
        <Field label="Professional role *" error={errors.role?.message}><Select {...register('role')}><option value="">Select your closest role</option>{specialistRoles.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Years of experience *" error={errors.yearsExperience?.message}><Input type="number" min="0" max="60" {...register('yearsExperience')}/></Field>
        <Field className="full" label="Core skills *" error={errors.skills?.message}><Textarea placeholder="List the technologies, disciplines and domains where you are strongest." {...register('skills')}/></Field>
        <Field label="Portfolio URL" error={errors.portfolioUrl?.message}><Input type="url" placeholder="https://" {...register('portfolioUrl')}/></Field><Field label="GitHub URL" error={errors.githubUrl?.message}><Input type="url" placeholder="https://github.com/" {...register('githubUrl')}/></Field>
        <Field label="LinkedIn URL" error={errors.linkedinUrl?.message}><Input type="url" placeholder="https://linkedin.com/in/" {...register('linkedinUrl')}/></Field><Field label="Availability *" error={errors.availability?.message}><Input placeholder="e.g. 15 hours/week from September" {...register('availability')}/></Field>
        <Field label="Preferred engagement *" error={errors.engagementType?.message}><Select {...register('engagementType')}><option value="">Select one</option>{engagement.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="CV * (PDF or DOCX, 8 MB max)"><Input type="file" required accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0])}/></Field>
        <Field className="full" label="Short introduction *" error={errors.introduction?.message}><Textarea placeholder="Tell us what you enjoy working on, how you collaborate and what you hope to contribute." {...register('introduction')}/></Field>
        <div className="field full"><label className="checkbox-row"><input type="checkbox" {...register('consent')}/><span>I consent to {company.name} storing my profile and contacting me about relevant future opportunities, as described in the <a className="underline" href="/privacy">privacy policy</a>. *</span></label>{errors.consent?.message&&<span className="field-error" role="alert">{errors.consent.message}</span>}</div><div className="field full"><TurnstileField onToken={token=>setValue('turnstileToken',token)}/></div>
      </div><div className="mt-7"><SubmitButton disabled={status.kind==='sending'}>{status.kind==='sending'?'Sending securely…':'Submit talent profile'}</SubmitButton>{status.kind!=='idle'&&<div className={`form-status ${status.kind==='error'?'error':'success'}`} role="status">{status.message}</div>}</div></form></div></section>
    <section className="section bg-white"><div className="container-shell max-w-4xl"><div className="flex gap-4 items-center mb-10"><CircleCheckBig className="text-[#167d63]"/><h2 className="heading-lg">Talent network questions</h2></div><Accordion items={networkFaq}/></div></section>
  </>;
}
