import { AlertTriangle, ArrowLeft, CheckCircle2, FileCheck2 } from 'lucide-react';
import { Link, useRouteError, useSearchParams } from 'react-router-dom';
import { SEO } from '../components/SEO';
import { ButtonLink, Crumbs } from '../components/ui';
import { company, projects } from '../content/site';

export function NotFoundPage(){return <><SEO title="Page not found" description="The requested page could not be found."/><section className="min-h-[70vh] grid place-items-center bg-ink text-white"><div className="container-shell text-center"><p className="text-mint font-bold">404</p><h1 className="display-page mt-6">This page took a wrong turn.</h1><p className="body-lg !text-[#b6c1c5] mt-6">The address may have changed, or the page no longer exists.</p><div className="mt-8"><ButtonLink to="/">Return home</ButtonLink></div></div></section></>}

export function ErrorPage(){const error=useRouteError();return <><SEO title="Something went wrong" description="An unexpected error occurred."/><section className="min-h-screen grid place-items-center bg-ink text-white"><div className="container-shell max-w-3xl text-center"><AlertTriangle className="text-mint mx-auto" size={42}/><h1 className="display-page mt-6">Something did not load correctly.</h1><p className="body-lg !text-[#b6c1c5] mt-6">Please return home and try again. No form submission should be assumed complete unless you received a reference number.</p>{import.meta.env.DEV&&<pre className="mt-6 whitespace-pre-wrap text-left text-xs text-red-200">{error instanceof Error?error.message:String(error)}</pre>}<div className="mt-8"><ButtonLink to="/">Return home</ButtonLink></div></div></section></>}

export function SubmissionSuccessPage(){const [params]=useSearchParams();const type=params.get('type');const reference=params.get('reference');if(!reference)return <NotFoundPage/>;const talent=type==='talent';return <><SEO title="Submission received" description="Your submission has been safely received." path="/submission-success"/><section className="min-h-[75vh] grid place-items-center"><div className="container-shell max-w-3xl text-center py-20"><CheckCircle2 size={52} className="mx-auto text-[#167d63]"/><p className="eyebrow justify-center text-[#167d63] mt-7">Submission confirmed</p><h1 className="display-page mt-7">Thank you. We have it.</h1><p className="body-lg mt-6">{talent?'Your profile is now in the talent network for consideration when a relevant opportunity becomes available.':'Your project context has been received and is ready for review.'}</p><div className="card mt-8 p-5"><span className="text-xs uppercase tracking-wider text-subtle">Reference number</span><strong className="block text-2xl mt-2 tracking-wide">{reference}</strong></div><p className="text-sm text-subtle mt-5">Keep this reference if you need to follow up or request an update.</p><Link to="/" className="text-link mt-8"><ArrowLeft size={16}/> Return home</Link></div></section></>}

export function PrivacyPage(){return <LegalPage type="privacy"/>} export function TermsPage(){return <LegalPage type="terms"/>} export function AccessibilityPage(){return <LegalPage type="accessibility"/>}
function LegalPage({type}:{type:'privacy'|'terms'|'accessibility'}){
  const content={privacy:{title:'Privacy policy',intro:'How information submitted through this website is intended to be handled.',sections:[['Information collected','Project enquiries may include contact, organization and project information. Talent profiles may include professional details and a private CV. Technical logs may record security and delivery events.'],['How it is used','Information is used to respond to enquiries, assess relevant collaboration opportunities, maintain security and meet legitimate record-keeping needs. It is not intended for sale.'],['Storage and access','Form records are stored in the configured database. Attachments are kept outside public web storage and accessed only through authenticated administrative routes. Retention periods must be finalized before launch.'],['Your choices',`Contact ${company.email} to request access, correction or deletion. Applicable requirements depend on where the consultancy and user are located.`]]},terms:{title:'Terms of use',intro:'The basic conditions for using this website and its materials.',sections:[['Website information','Content is provided for general information and does not constitute a binding proposal, legal advice or a guarantee of project availability.'],['Intellectual property','Unless otherwise stated, the website design and original content belong to the consultancy. Client project materials remain subject to their respective rights and permissions.'],['External links','External services may have separate terms and privacy practices. Their availability and content are not controlled by this website.'],['Limitation template','Any final limitation-of-liability language should be reviewed for the relevant jurisdictions before publication.']]},accessibility:{title:'Accessibility statement',intro:'Our commitment to a website that more people can use.',sections:[['Our approach','The website is designed toward WCAG 2.2 AA with semantic landmarks, keyboard access, visible focus, responsive layouts, form labels and reduced-motion support.'],['Known limitations','Third-party services such as file upload, anti-spam or scheduling widgets must be checked after their production configuration is added.'],['Feedback',`If you encounter an access barrier, contact ${company.email} and describe the page, device and assistive technology involved.`],['Continuous improvement','Accessibility is treated as ongoing product quality. Feedback should be logged, prioritized and verified after changes.']]}}[type];
  return <><SEO title={content.title} description={content.intro} path={`/${type}`}/><section className="page-hero grid-lines"><div className="container-shell max-w-5xl"><Crumbs items={[{label:'Home',to:'/'},{label:content.title}]}/><h1 className="display-page mt-8">{content.title}</h1><p className="body-lg mt-6">{content.intro}</p></div></section><article className="section"><div className="container-shell article-body"><div className="rounded-lg border border-[#e0c38d] bg-[#f6e9d1] p-4 text-sm text-[#704617]"><strong>Template for professional review.</strong> This content is operational guidance, not definitive legal advice. Replace placeholder contact and retention details before launch.</div>{content.sections.map(([title,text])=><section className="mt-12" key={title}><h2 className="heading-lg">{title}</h2><p>{text}</p></section>)}</div></article></>;
}

export function ContentGuidePage(){const fields=['Consultancy name and approved logo','Business email, phone, WhatsApp and final address','Founder name, biography and approved portrait','Seven approved project names and client/publication status','Business problem, users, solution and key features for each project','Technology stack and security measures for each project','Verified qualitative or quantitative result for each project','Approved project screenshots and alt text','Any client testimonial with explicit publication permission','Final social links and canonical domain','Form response-time commitment and data-retention periods','Legal text reviewed for applicable jurisdictions'];return <><SEO title="Content replacement guide" description="The real company information still required before publication." path="/content-guide"/><section className="page-hero grid-lines"><div className="container-shell"><Crumbs items={[{label:'Home',to:'/'},{label:'Content guide'}]}/><p className="eyebrow text-mint">Launch checklist</p><h1 className="display-page mt-8 max-w-5xl">Replace placeholders with verified, approved facts.</h1><p className="body-lg mt-7">Most editable public information lives in <code>src/content/site.ts</code>. Project records are structured so confidential details can remain protected.</p></div></section><section className="section"><div className="container-shell max-w-4xl"><div className="grid gap-3">{fields.map((field,index)=><div className="card p-5 flex items-center gap-4" key={field}><FileCheck2 className="text-[#167d63] shrink-0"/><span className="text-xs text-subtle">{String(index+1).padStart(2,'0')}</span><p className="font-bold">{field}</p></div>)}</div><div className="mt-12"><h2 className="heading-lg">Project record completeness</h2><p className="body-lg mt-4">{projects.filter(p=>p.approved).length} of {projects.length} project records are approved for publication.</p></div></div></section></>}
