import { Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { FinalCTA } from '../components/Layout';
import { EditorialPageHero } from '../components/EditorialPageHero';
import { ProjectPreviewVisual } from '../components/HeroVisuals';
import { ProjectCard } from '../components/ProjectCard';
import { SEO } from '../components/SEO';
import { ButtonLink, SectionIntro } from '../components/ui';
import { industries, projects, services } from '../content/site';
import { NotFoundPage } from './UtilityPages';

export default function WorkPage() {
  const [query,setQuery]=useState(''); const [industry,setIndustry]=useState(''); const [service,setService]=useState(''); const [technology,setTechnology]=useState(''); const [status,setStatus]=useState(''); const [visibility,setVisibility]=useState('');
  const technologies=[...new Set(projects.flatMap(p=>p.technology))];
  const filtered=useMemo(()=>projects.filter(p=>(!query||`${p.name} ${p.client} ${p.technology.join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(!industry||p.industry===industry)&&(!service||p.services.includes(service))&&(!technology||p.technology.includes(technology))&&(!status||p.status===status)&&(!visibility||p.visibility===visibility)),[query,industry,service,technology,status,visibility]);
  return <>
    <SEO title="Selected work" description="Explore structured case studies from production technology projects, with confidential information protected." path="/work" />
    <EditorialPageHero variant="project" eyebrow="Selected work" title="Production systems built to solve real problems." description="Explore how we turn complex workflows and organizational needs into maintainable digital products." breadcrumbs={[{label:'Home',to:'/'},{label:'Work'}]} visual={<ProjectPreviewVisual label="From operational friction to a connected system"/>}/>
    <section className="section"><div className="container-shell"><div className="filter-bar" aria-label="Filter projects"><div className="search-wrap"><Search size={17}/><input className="search-input" type="search" placeholder="Search work or technology" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search projects"/></div><select className="filter-select" value={industry} onChange={e=>setIndustry(e.target.value)} aria-label="Filter by industry"><option value="">All industries</option>{industries.map(i=><option key={i.slug}>{i.name}</option>)}</select><select className="filter-select" value={service} onChange={e=>setService(e.target.value)} aria-label="Filter by service"><option value="">All services</option>{services.map(s=><option key={s.slug}>{s.name}</option>)}</select><select className="filter-select" value={technology} onChange={e=>setTechnology(e.target.value)} aria-label="Filter by technology"><option value="">All technologies</option>{technologies.map(item=><option key={item}>{item}</option>)}</select><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter by production status"><option value="">All production statuses</option><option>In production</option></select><select className="filter-select" value={visibility} onChange={e=>setVisibility(e.target.value)} aria-label="Filter by publication status"><option value="">All publication levels</option><option>Public</option><option>Partially anonymized</option><option>Confidential summary only</option></select></div><p className="mb-6 text-sm text-subtle" aria-live="polite">Showing {filtered.length} of {projects.length} projects</p>{filtered.length?<div className="project-grid">{filtered.map(p=><ProjectCard project={p} key={p.slug}/>)}</div>:<div className="card p-12 text-center"><h2 className="heading-md">No projects match those filters.</h2><button className="btn btn-outline mt-6" onClick={()=>{setQuery('');setIndustry('');setService('');setTechnology('');setStatus('');setVisibility('')}}>Clear filters</button></div>}</div></section><FinalCTA />
  </>;
}

export function CaseStudyPage() {
  const {slug}=useParams(); const project=projects.find(item=>item.slug===slug); if(!project)return <NotFoundPage/>;
  const publicTitle=project.approved?project.name:'Confidential production system';
  const publicOutcome=project.approved?project.result:'Project identity and operational details are withheld until publication is approved.';
  const sections=[['Project overview',`${project.name} is one of seven systems currently in production. Identifying information is withheld until approved for publication.`],['Client context',project.client],['The challenge',project.challenge],['Discovery & constraints','Workflow, user, connectivity, security and implementation constraints are awaiting approved project documentation.'],['The solution',project.solution],['Architecture & delivery','Architecture details will be added only after a confidentiality and security review.'],['Key features','Approved feature list pending.'],['Security & reliability','Specific controls remain confidential until the client confirms what may be published.'],['Results & operational impact',project.result]];
  return <>
    <SEO title={`${project.name} case study`} description={project.result} path={`/work/${project.slug}`}/>
    <EditorialPageHero variant="project" eyebrow={project.industry} title={publicTitle} description={publicOutcome} breadcrumbs={[{label:'Home',to:'/'},{label:'Work',to:'/work'},{label:publicTitle}]} meta={<div className="flex flex-wrap gap-2"><span className="tag tag-dark">{project.status}</span><span className="tag tag-dark">{project.services[0]}</span><span className="tag tag-dark">{project.visibility}</span></div>} visual={<ProjectPreviewVisual label={project.approved?project.name:'Operational workflow'}/>}/>
    <section className="section"><div className="container-shell"><div className={`project-visual ${project.accent} !h-[min(55vw,42rem)] rounded-2xl`}><div className="project-window"><div className="project-toolbar"><i/><i/><i/></div><div className="project-ui"><div><div className="ui-line"/><div className="ui-line short"/><div className="ui-line"/></div><div><div className="ui-line short"/><div className="ui-tile"/><div className="ui-tile"/></div></div></div></div><div className="detail-layout mt-20"><aside><p className="eyebrow text-[#167d63]">Case study record</p><div className="mt-7 grid gap-5 text-sm"><div><span className="text-subtle block">Industry</span><b>{project.industry}</b></div><div><span className="text-subtle block">Services</span><b>{project.services.join(', ')}</b></div><div><span className="text-subtle block">Technology</span><b>{project.technology.join(', ')}</b></div></div></aside><div className="grid gap-12">{sections.map(([title,text])=><section key={title}><h2 className="heading-lg">{title}</h2><p className="body-lg mt-5">{text}</p></section>)}</div></div></div></section>
    <section className="section bg-[#e6eae7]"><div className="container-shell"><SectionIntro eyebrow="Gallery" title="Approved interface images will appear here."/><div className="grid sm:grid-cols-3 gap-4">{[1,2,3].map(n=><div className="aspect-[4/3] rounded-xl border border-dashed border-[#9aa8a1] grid place-items-center text-sm text-subtle" key={n}>Screenshot {n} pending</div>)}</div></div></section>
    <section className="section-sm"><div className="container-shell cta-panel"><h2 className="heading-lg max-w-3xl">Could a better system remove friction from your operation?</h2><div className="mt-7"><ButtonLink to="/start-a-project">Start a project</ButtonLink></div></div></section><FinalCTA />
  </>;
}
