import { lazy, Suspense } from 'react';
import { Navigate, Route, Routes } from 'react-router-dom';
import { Layout } from './components/Layout';
import { AccessibilityPage, ContentGuidePage, ErrorPage, NotFoundPage, PrivacyPage, SubmissionSuccessPage, TermsPage } from './pages/UtilityPages';

const HomePage=lazy(()=>import('./pages/HomePage')); const ServicesPage=lazy(()=>import('./pages/ServicesPage')); const ServiceDetailPage=lazy(()=>import('./pages/ServicesPage').then(m=>({default:m.ServiceDetailPage})));
const IndustriesPage=lazy(()=>import('./pages/IndustriesPage')); const IndustryDetailPage=lazy(()=>import('./pages/IndustriesPage').then(m=>({default:m.IndustryDetailPage})));
const WorkPage=lazy(()=>import('./pages/WorkPage')); const CaseStudyPage=lazy(()=>import('./pages/WorkPage').then(m=>({default:m.CaseStudyPage})));
const AboutPage=lazy(()=>import('./pages/AboutPage')); const InsightsPage=lazy(()=>import('./pages/InsightsPage')); const ArticlePage=lazy(()=>import('./pages/InsightsPage').then(m=>({default:m.ArticlePage})));
const StartProjectPage=lazy(()=>import('./pages/StartProjectPage')); const JoinPage=lazy(()=>import('./pages/JoinPage')); const AdminPage=lazy(()=>import('./pages/AdminPage'));
function Loading(){return <div className="min-h-[50vh] grid place-items-center" role="status"><span className="eyebrow text-[#167d63]">Loading</span></div>}
export default function App(){return <Suspense fallback={<Loading/>}><Routes><Route path="/admin" element={<AdminPage/>}/><Route element={<Layout/>} errorElement={<ErrorPage/>}><Route index element={<HomePage/>}/><Route path="services" element={<ServicesPage/>}/><Route path="services/:slug" element={<ServiceDetailPage/>}/><Route path="industries" element={<IndustriesPage/>}/><Route path="industries/:slug" element={<IndustryDetailPage/>}/><Route path="work" element={<WorkPage/>}/><Route path="work/:slug" element={<CaseStudyPage/>}/><Route path="about" element={<AboutPage/>}/><Route path="insights" element={<InsightsPage/>}/><Route path="insights/:slug" element={<ArticlePage/>}/><Route path="join" element={<JoinPage/>}/><Route path="start-a-project" element={<StartProjectPage/>}/><Route path="submission-success" element={<SubmissionSuccessPage/>}/><Route path="privacy" element={<PrivacyPage/>}/><Route path="terms" element={<TermsPage/>}/><Route path="accessibility" element={<AccessibilityPage/>}/><Route path="content-guide" element={<ContentGuidePage/>}/><Route path="404" element={<NotFoundPage/>}/><Route path="*" element={<NotFoundPage/>}/></Route><Route path="/start" element={<Navigate to="/start-a-project" replace/>}/></Routes></Suspense>}
